from typing import Protocol

from mr_review.domain import Discussion, MergeRef, MergeRequest


class Forge(Protocol):
    def fetch_mr(self, mr: MergeRef) -> MergeRequest: ...

    def list_discussions(self, mr: MergeRef) -> list[Discussion]: ...

    def reply(self, mr: MergeRef, discussion_id: str, body: str) -> None: ...

    def edit_note(self, mr: MergeRef, discussion_id: str, note_id: str, body: str) -> None: ...

    def set_resolved(self, mr: MergeRef, discussion_id: str, resolved: bool) -> None: ...
